server:
  port: 8090

spring:
  main:
    banner-mode: off
  cloud:
    vault:
      token: 00000000-0000-0000-00000000000
      scheme: http
      application-name: avizandum
      host: 127.0.0.1
      port: 8200
  profiles:
    active: dev

---

spring:
  cloud:
    aws:
      region:
        static: eu-north-1
  datasource:
    url: jdbc:mysql://thor:3306/avizandum2
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:data-mysql.sql
  config:
    activate:
      on-profile: dev

aws:
  region: eu-north-1
  sqs:
    queue: avizandum
    access-key: ${awsaccesskey}
    secret-key: ${awssecretkey}
    queue-url: ${awsqueueurl}
  config:
    activate:
      on-profile: dev
    
---
spring:
  cloud:
    aws:
      region:
        static: eu-north-1
  datasource:
    url: jdbc:h2:mem:avizandum2
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: test

aws:
  region: eu-north-1
  sqs:
    queue: avizandum
    access-key: ${awsaccesskey}
    secret-key: ${awssecretkey}
    queue-url: ${awsqueueurl}
  config:
    activate:
      on-profile: test