server:
  port: 8090

spring:
  main:
    banner-mode: off
  cloud:
    vault:
      token: 00000000-0000-0000-00000000000
      scheme: http
      application-name: avizandum
      host: 127.0.0.1
      port: 8200
  profiles:
    active: dev

---

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://thor:3306/avizandum2
    username: ${dbusername}
    password: ${dbpassword}
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  
  
  