insert into TERRAIN (ID, NAME) values (1, 'Bog')
insert into TERRAIN (ID, NAME) values (2, 'Forest')
insert into TERRAIN (ID, NAME) values (3, 'Plains')
insert into DISTRICT (ID, TERRAIN_ID, NAME) values (1, 1, 'Bogtown')
insert into DOMAIN (ID, NAME, OWNER_ID) values (1, 'Bogtopia', 1)